#!/bin/bash

#listaArquivos=("./V8-assemblies/asm/Baseline_p1-all.asm" "./V8-assemblies/asm/Baseline_p1-base.asm")
listaArquivos=("./V8-assemblies/asm/Baseline_p1-all.asm" "./V8-assemblies/asm/Baseline_p1-base.asm" "./V8-assemblies/asm/Baseline_p1-definitions.asm" "./V8-assemblies/asm/Baseline_p1-ifelse.asm" "./V8-assemblies/asm/Baseline_p1-junkcode.asm" "./V8-assemblies/asm/Baseline_p1-while.asm" "./V8-assemblies/asm/Baseline_p2-all.asm" "./V8-assemblies/asm/Baseline_p2-base.asm" "./V8-assemblies/asm/Baseline_p2-definitions.asm" "./V8-assemblies/asm/Baseline_p2-ifelse.asm" "./V8-assemblies/asm/Baseline_p2-junkcode.asm" "./V8-assemblies/asm/Baseline_p2-while.asm" "./V8-assemblies/asm/SparkLevFan_p1-all.asm" "./V8-assemblies/asm/SparkLevFan_p1-base.asm" "./V8-assemblies/asm/SparkLevFan_p1-definitions.asm" "./V8-assemblies/asm/SparkLevFan_p1-ifelse.asm" "./V8-assemblies/asm/SparkLevFan_p1-junkcode.asm" "./V8-assemblies/asm/SparkLevFan_p1-while.asm" "./V8-assemblies/asm/SparkLevFan_p2-all.asm" "./V8-assemblies/asm/SparkLevFan_p2-base.asm" "./V8-assemblies/asm/SparkLevFan_p2-definitions.asm" "./V8-assemblies/asm/SparkLevFan_p2-ifelse.asm" "./V8-assemblies/asm/SparkLevFan_p2-junkcode.asm" "./V8-assemblies/asm/SparkLevFan_p2-while.asm" "./V8-assemblies/asm/SparkLev_p1-all.asm" "./V8-assemblies/asm/SparkLev_p1-base.asm" "./V8-assemblies/asm/SparkLev_p1-definitions.asm" "./V8-assemblies/asm/SparkLev_p1-ifelse.asm" "./V8-assemblies/asm/SparkLev_p1-junkcode.asm" "./V8-assemblies/asm/SparkLev_p1-while.asm" "./V8-assemblies/asm/SparkLev_p2-all.asm" "./V8-assemblies/asm/SparkLev_p2-base.asm" "./V8-assemblies/asm/SparkLev_p2-definitions.asm" "./V8-assemblies/asm/SparkLev_p2-ifelse.asm" "./V8-assemblies/asm/SparkLev_p2-junkcode.asm" "./V8-assemblies/asm/SparkLev_p2-while.asm" "./V8-assemblies/asm/SparkLevShaft_p1-all.asm" "./V8-assemblies/asm/SparkLevShaft_p1-base.asm" "./V8-assemblies/asm/SparkLevShaft_p1-definitions.asm" "./V8-assemblies/asm/SparkLevShaft_p1-ifelse.asm" "./V8-assemblies/asm/SparkLevShaft_p1-junkcode.asm" "./V8-assemblies/asm/SparkLevShaft_p1-while.asm" "./V8-assemblies/asm/SparkLevShaft_p2-all.asm" "./V8-assemblies/asm/SparkLevShaft_p2-base.asm" "./V8-assemblies/asm/SparkLevShaft_p2-definitions.asm" "./V8-assemblies/asm/SparkLevShaft_p2-ifelse.asm" "./V8-assemblies/asm/SparkLevShaft_p2-junkcode.asm" "./V8-assemblies/asm/SparkLevShaft_p2-while.asm")


for asm in "${listaArquivos[@]}"; do
    echo "...Converting ${asm}..." &&
    python3 v8_to_bin.py $asm "./asm-to-bins/${asm%.*}.bin"
done
