#!/bin/bash

listaArquivos=("./asm-to-bins/V8-assemblies/asm/Baseline_p1-all.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p1-base.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p1-definitions.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p1-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p1-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p1-while.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p2-all.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p2-base.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p2-definitions.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p2-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p2-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/Baseline_p2-while.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p1-all.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p1-base.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p1-definitions.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p1-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p1-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p1-while.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p2-all.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p2-base.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p2-definitions.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p2-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p2-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevFan_p2-while.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p1-all.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p1-base.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p1-definitions.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p1-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p1-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p1-while.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p2-all.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p2-base.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p2-definitions.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p2-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p2-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/SparkLev_p2-while.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p1-all.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p1-base.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p1-definitions.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p1-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p1-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p1-while.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p2-all.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p2-base.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p2-definitions.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p2-ifelse.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p2-junkcode.bin" "./asm-to-bins/V8-assemblies/asm/SparkLevShaft_p2-while.bin")


for bin1 in "${listaArquivos[@]}"; do
    for bin2 in "${listaArquivos[@]}"; do
        echo "${bin1} X ${bin2}" >> radiff-output.txt &&
        radiff2 -a x86 -b 64 -ss $bin1 $bin2 >> radiff-output.txt
    done
done
